#!/bin/bash
#SBATCH --partition=a100_short
#SBATCH --job-name=MdlPooled
#SBATCH --mem-per-cpu=6G
#SBATCH --time=03-00:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=8
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --mail-type=END
#SBATCH --mail-user=bs3667@nyu.edu
cd ~/Noise/Modelfit
module load cuda/11.8
module load matlab/R2021b
matlab -nodisplay -r ModelFit_Pooled
