#!/bin/bash
#SBATCH --partition=a100_short
#SBATCH --job-name=Fig1
#SBATCH --mem-per-cpu=6G
#SBATCH --time=3-00:00:00
#SBATCH --tasks=1
#SBATCH --cpus-per-task=20
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:4
#SBATCH --mail-type=END
#SBATCH --mail-user=bs3667@nyu.edu
cd ~/Noise/ModelSimulationCode
module load cuda/11.8
module load matlab/R2023a
matlab -nodisplay -r Fig1

